import Header from "@/components/Header";
import "../globals.css";
import type { Metadata } from "next";
import { Tinos } from "next/font/google";

const tinos = Tinos({ subsets: ["latin"],
  weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${tinos.className} bg-[#1E1E1E]`}>
        {/* Header */}
        <Header />
        {/* Banner */}

        {children}
      </body>
    </html>
  );
}
